server:
  port: 9000
spring:
  application:
    name: coupon-gateway
eureka:
  client:
    #    标识是否从eureka server 获取注册信息，默认是true ，如果是一个单节点的 eureka server
    #    不需要同步其他节点的数据，设置为false
#    fetch-registry: false
    #    是否将自己注册到eureka server ，默认是 true，单节点 设置为false
#    register-with-eureka: false
      service-url:
        defaultZone: http://server1:8000/eureka/