spring:
  application:
    name: coupon-eureka
    profiles: server1
server:
  port: 8000

eureka:
  instance:
#    hostname: localhost
    hostname: server1
  client:
#    标识是否从eureka server 获取注册信息，默认是true ，如果是一个单节点的 eureka server
#    不需要同步其他节点的数据，设置为false
    fetch-registry: false
#    是否将自己注册到eureka server ，默认是 true，单节点 设置为false
    register-with-eureka: false
#    设置eureka server 所在的地址，查询服务和注册服务需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
